"""Les modèles pydantic — la SOURCE du contrat OpenAPI."""

from __future__ import annotations

from .common import (
    REPONSES_ERREUR,
    ErreurPennylane,
    Lien,
    Page,
    Permissif,
    Reference,
    invented,
    unverified,
)
from .entities import (
    Categorie,
    CompteBancaire,
    ComptePlan,
    Contact,
    Ecriture,
    ElementGenerique,
    EtablissementBancaire,
    EvenementChangelog,
    Exercice,
    FactureClient,
    FactureFournisseur,
    Fournisseur,
    GroupeCategories,
    Journal,
    LigneBalance,
    LigneEcriture,
    LigneFacture,
    Produit,
    ProfilUtilisateur,
    Reglement,
    TiersClient,
    Transaction,
)

__all__ = [
    "REPONSES_ERREUR",
    "Categorie",
    "CompteBancaire",
    "ComptePlan",
    "Contact",
    "Ecriture",
    "ElementGenerique",
    "ErreurPennylane",
    "EtablissementBancaire",
    "EvenementChangelog",
    "Exercice",
    "FactureClient",
    "FactureFournisseur",
    "Fournisseur",
    "GroupeCategories",
    "Journal",
    "Lien",
    "LigneBalance",
    "LigneEcriture",
    "LigneFacture",
    "Page",
    "Permissif",
    "Produit",
    "ProfilUtilisateur",
    "Reference",
    "Reglement",
    "TiersClient",
    "Transaction",
    "invented",
    "unverified",
]
